---

- name: Create Additional Tower Credential Types
  awx.awx.tower_credential_type:
    name: "{{ item.name }}"
    description: "{{ item.description | default(omit) }}"
    kind: "{{ item.kind }}"
    inputs: "{{ item.inputs | default(omit) }}"
    injectors: "{{ item.injectors | default(omit) }}"
    state: present
    validate_certs: no
    tower_host: "{{ awx_web_url }}"
    tower_username: "{{ awx_admin_user }}"
    tower_password: "{{ awx_admin_password }}"
  loop: "{{ awx_credential_types }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - awx_credential_types is defined
    - awx_credential_types != None

- name: Create Tower credentials
  awx.awx.tower_credential:
    name: "{{ item.name }}"
    organization: "{{ item.organization | default('Default') }}"
    state: "{{ item.state | default('present') }}"
    inputs: "{{ item.inputs|default(omit) }}"
    credential_type: "{{ item.credential_type }}"
    validate_certs: no
    tower_host: "{{ awx_web_url }}"
    tower_username: "{{ awx_admin_user }}"
    tower_password: "{{ awx_admin_password }}"
  loop: "{{ awx_credentials }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - awx_credentials is defined
    - awx_credentials != None
  changed_when: False