---
- name: Add projects to Tower
  awx.awx.tower_project:
    name: "{{ item.name }}"
    description: "{{ item.description | default(omit) }}"
    scm_type: "{{ item.scm_type | default(omit) }}"
    scm_credential: "{{ item.scm_credential | default(omit) }}"
    scm_clean: "{{ item.scm_clean | default(omit) }}"
    scm_branch: "{{ item.scm_branch | default(omit) }}"
    scm_update_on_launch: "{{ item.scm_update_on_launch | default(omit) }}"
    scm_update_cache_timeout: "{{ item.scm_update_cache_timeout | default(omit) }}"
    scm_url: "{{ item.scm_url | default(omit) }}"
    local_path: "{{ item.local_path | default(omit) }}"
    organization: "{{ item.organization | default('Default') }}"
    webhook_service: "{{ item.webhook_service | default(omit) }}"
    webhook_credential: "{{ item.webhook_credential | default(omit) }}"
    state: "{{ item.state | default('present') }}"
    validate_certs: false
    tower_host: "{{ awx_web_url }}"
    tower_username: "{{ awx_admin_user }}"
    tower_password: "{{ awx_admin_password }}"
  loop: "{{ awx_projects }}"
  loop_control:
    label: "{{ item.name }}"
  register: project_import
  when:
    - awx_projects is defined
    - awx_projects != None
  changed_when: false

- name: Export tower assets to refresh playbook data
  awx.awx.tower_receive:
    all: true
    validate_certs: false
    tower_host: "{{ awx_web_url }}"
    tower_username: "{{ awx_admin_user }}"
    tower_password: "{{ awx_admin_password }}"
  register: towerassets
