---
- name: "Disable SELinux, Configure FirewallD ports to ACCEPT [RHEL/CentOS]"
  block:
    - name: Disable SELinux
      ansible.posix.selinux:
        state: disabled
    - name: Configure Firewalld allowed ports
      ansible.posix.firewalld:
        port: "{{ item }}"
        permanent: true
        immediate: true
        state: enabled
      loop: "{{ awx_allowed_ports }}"
  when: ansible_os_family == "RedHat"
  tags:
    - always

- name: Assure variables are set
  ansible.builtin.import_tasks: assertions.yml

- name: Build config files for AWX services
  ansible.builtin.import_tasks: config-files.yml
