---
- set_fact:
    awx_containers_running: False

- name: "Check for {{ awx_web_container_name }} container"
  shell: 'docker ps | egrep -q "{{ awx_web_container_name}}"'
  register: awx_web_container_present
  changed_when: False
  ignore_errors: True

- name: "Check for {{ awx_task_container_name }} container"
  shell: 'docker ps | egrep -q "{{ awx_task_container_name }}"'
  register: awx_task_container_present
  changed_when: False
  ignore_errors: True

- set_fact:
    awx_containers_running: True
  when:
    - awx_task_container_present
    - awx_web_container_present
