---
- name: Clear AWX/Tower flag
  ansible.builtin.set_fact:
    awx_containers_running: false

- name: "Check for {{ awx_web_container_name }} container"
  ansible.builtin.shell: 'docker ps | egrep -q "{{ awx_web_container_name}}"'
  register: awx_web_container_present
  changed_when: false
  ignore_errors: true

- name: "Check for {{ awx_task_container_name }} container"
  ansible.builtin.shell: 'docker ps | egrep -q "{{ awx_task_container_name }}"'
  register: awx_task_container_present
  changed_when: false
  ignore_errors: true

- name: Set AWX/Tower flag
  ansible.builtin.set_fact:
    awx_containers_running: true
  when:
    - awx_task_container_present
    - awx_web_container_present
